@startuml
scale 1000 width

state "Карта не активирована" as NotActivated

state Активная {
    [*] -> Обычная
    Обычная --> Премиум : [Статус клиента\nизменен на Премиум]
    Премиум --> Обычная : [Статус клиента\nизменен на Стандарт]
    
    state "Обычная" as Обычная
    state "Премиум" as Премиум
}

NotActivated --> Активная : [Активация карты]

Активная --> Заблокированная : [Попытка мошенничества]
Активная --> Утерянная : [Карта утеряна]
Активная --> Просроченная : [Истек срок действия]

Заблокированная --> Активная : [Проверка на операцию \n мошенничества пройдена,\n не подтверждена]
Утерянная --> Активная : [Карта найдена]
Просроченная --> [*] : [Уничтожение карты]
Просроченная -->NotActivated: [Перевыпуск карты]

note right of Просроченная
Истек срок действия карты по месяцу
и году окончания
end note

note right of Утерянная
Пользователь карты утратил контроль над картой
end note

@enduml