@startuml
start


:Регистрация/авторизация клиента;

if (У клиента есть учетная запись) then(да)
    :входит в существующий аккаунт;
else (нет)
    :Клиент регистрируется на сайте;
endif
:оформление заказа;

fork
:Клиент выбирает товары;

fork again
:добавляет их в корзину;
fork end

: Клиент переходит к оформлению заказа;
fork
: выбирает способ доставки;
fork again
: выбор способа оплаты;
fork end
:Проверка наличия товара на складе;
:Система проверяет наличие каждого товара в выбранных количествах;
if(товар отсутствует) then(да)
fork
:Уведомление клиента о недоступности товара;
fork again
:Возможность выбрать альтернативный товар или удалить отсутствующий из заказа;
fork end
else(нет)
fork
:Оплата заказа;

fork again
:Подготовка товара к отправке;
fork end
if (Если оплата прошла успешно и товар готов к отправке) then (да)
fork
:Генерируется счёт-фактура;
fork again
:Отправляется уведомление клиенту о подтверждении заказа и статусе доставки;
fork again
:Заказ переходит в статус «Отправлен»;
fork end
else(нет)
:Если оплата не прошла;
fork
:Отправляется уведомление клиенту о проблеме с платежом;
fork again
:Клиенту предлагается повторить попытку оплаты или изменить способ оплаты;
fork end
if(Если клиента не устраивает решение) then (нет)
:Заказ отменяется;
:Клиенту возвращаются средства (если были списаны);
else(да)

endif

@enduml
